name: Publish Content
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --global user.email "${GITHUB_EMAIL}"
        git config --global user.name "${GITHUB_USER}"
        git fetch --unshallow
        rm -rf public
        echo "checkout to master as worktree"
        git worktree prune && git worktree add -B master public origin/master
        
        echo "generate static content in public"
        docker run --rm -v $(pwd):/site -v $(pwd)/public:/site/public l1990790120/hugo:0.64.1-p ""
        echo "push public to master"
        cd public
        git add --all
        git commit -m "Publishing to master"
        git push
      env:
        GITHUB_EMAIL: ${{ secrets.GITHUBEMAIL }}
        GITHUB_USER: ${{ secrets.GITHUBUSER }}  
